#!/usr/bin/env zsh
# Script for automating an F1 points game

#source libraries

source lib/config.shlib

#constants

ROOT_PATH=$(pwd)
CONFIG_FILE="${ROOT_PATH}/config/config.cfg"
PLAYER_CONFIG="${ROOT_PATH}/config/player.cfg"
BANNER_FILE="${ROOT_PATH}/resources/banner.txt"
CAR_FILE="${ROOT_PATH}/resources/car.txt"

typeset -a DEFINED_PROPERTIES=("NUMBER_OF_PLAYERS", "DRIVERS_PER_PLAYER")

VERSION=0.0.1

typeset -a players=()
typeset -a drivers=()
typeset -A assigned_drivers=()
typeset -A player_points=()

# declare functions

#displays a useful help message
helpFunction() {

print \\n
print "Usage: $ZSH_ARGZERO [OPTION]..."
print "Automises tasks for an F1 Points Game by drawing drivers, allocating points, etc."
print \\n
print "Options: (Mandatory arguments to long options are mandatory for short options too)"
print \\t "    --car                            try me out!"
print \\t "-d, --draw                           performs a draw, assigning the configured amount of drivers to each player"
print \\t "-p, --points                         allocates points based on the latest race to each player"
print \\t "-c, --config key:value               configures the supplied property. available: ${DEFINED_PROPERTIES}"
print \\t "-h, --help                           displays this help and exits"
print \\n


exit 0

}

printError() {
    echo -e "\033[1;31m[ERROR] ${1}\033[0m"
}

printInfo() {
    echo -e "\033[1;36m[INFO] ${1}\033[0m"
}

printOK() {
    echo -e "\033[1;32m[INFO] ${1}\033[0m"
}

welcome() {

    print \\n
    print "Welcome to the F1 Points Game utility!"
    print "If you are unsure about how to proceed, please run the following for a list of available commands:"
    print \\t "$ $ZSH_ARGZERO --help"
    print \\n

}

#prints a cool banner of the utility name
printBanner() {
    echo
    cat resources/banner.txt
    echo "Version: ${VERSION}"
    echo
}

#prints a cool ACII art image of an F1 car
printCar() {
    print "Here is a cool image of an F1 car:"
    echo
    cat resources/car.txt
    echo
}

#assigns the configured amount of drivers to each player
performDraw() {

    performConfigCheck

}

#allocates points based on the lastest race result to each player
allocatePoints() {

    performConfigCheck

}

#checks whether the system the utility is used on meets all requirements
performSystemCheck() {

    # TODO: check for correct shell, jq, possibly getopt etc

    # might need this for compatibilty?
    #if [ -n "$ZSH_VERSION" ]; then emulate -L ksh; fi

    getoptMacOS

}

#checks whether the utility is correctly configured
performConfigCheck() {

    local number_of_players=$(config_get $CONFIG_FILE NUMBER_OF_PLAYERS)

    echo "NUMBER_OF_PLAYERS -> ${number_of_players}"

    if [[ $number_of_players = 0 ]]; then
        printError "Players are not onfigured. Please load players individually or load initialisation file"
        exit 1
    fi

    local drivers_per_player=$(config_get $CONFIG_FILE DRIVERS_PER_PLAYER)

    echo "DRIVERS_PER_PLAYER -> ${drivers_per_player}"

    if [[ $drivers_per_player = 0 ]]; then
        printError "Drivers per Player is not onfigured. Please configure DRIVERS_PER_PLAYER"
        exit 1
    fi


}

#configures the supplied property
configureProperty() {

    local key_value="$1"

    if [[ $key_value != *":"* ]]; then
        echo "Please provide property in the format key=value, eg DRIVERS_PER_PLAYER:2"
        exit 1
    fi

    local parts=(${(s/:/)key_value})

    local key=$parts[1]
    local value=$parts[2]

    readonly returned_key="$(config_check $CONFIG_FILE $key)"

    if [[ "${returned_key}" != "${key}" ]]; then
        printError "Key ${key} not found. Please specify a defined property. available: ${DEFINED_PROPERTIES}"
        exit 1
    fi

    echo "Configuring ${key} with ${value}"

    # TODO: write value to file

}

getoptMacOS() {

    if [[ "$(uname -s)" == 'Darwin' ]]; then
        if [[ ! -f /usr/local/opt/gnu-getopt/bin/getopt ]]; then
            if [[ "${SHELL}" == *"bin/fish"* ]]; then
                printError "The fish shell is not supported. Please use bash or zsh"
                exit 1
            fi
            printError "Please install gnu-getopt via Homebrew with: brew install gnu-getopt"
            exit 1
        else
            export PATH="$(brew --prefix gnu-getopt)/bin:$PATH"
        fi
    fi
}

#script start

echo
printBanner

performSystemCheck
# performConfigCheck

TEMP=$(getopt -o dpc:h --long car,draw,points,config:,help -n 'f1points' -- "$@")

if [ $? != 0 ] ; then echo "Terminating..." >&2 ; exit 1 ; fi

eval set -- "$TEMP"

while true; do
    case "$1" in
        --car ) printCar; break ;;
        -d | --draw ) performDraw; break;;
        -p | --points ) allocatePoints; break ;;
        -c | --config ) configureProperty "$2"; shift 2; break ;;
        -h | --help ) helpFunction; break ;;
        -- ) welcome; shift; break ;;
        * ) echo "*"; break ;;
    esac
done